name: CI Workflow

on:
  push:
    branches:
      - 'main' #Apenas no branch principal
    paths:
      - 'back-end/**' # Especifica a pasta onde vai rodar o teste

jobs:
  build:
    runs-on: ubuntu-latest # Máquina virtual onde vai ser rodado
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3 # É como se fosse um import
        with: # Pega esses comandos.
          java-version: '11'
          distribution: 'zulu'
      - name: Compilação / Test/ Package
        run: mvn --activate-profiles prod package
# O hifén indica um passo, e tudo que não tem hífen que vem depois estão incluidos no passo.
    
